blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/stephendltg/electron-sample/discussions/categories/q-a
    about: Use GitHub discussions for message-board style questions and discussions.
